name: aks-acr-integratedtests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NOME_APLICACAO: workeracoes
  NOME_IMAGEM: workeracoeskafka
  PATH_PROJETO: ./WorkerAcoes
  PATH_PROJETO_TESTES: ./WorkerAcoes.IntegrationTests
  FILE_LOG_EXECUCAO_WORKERACOES: log-execucao-workeracoes.txt
  AZURE_RESOURCE_GROUP_K8S: TesteKubernetes
  AZURE_CLUSTER_K8S: AKSCluster
  NAMESPACE_K8S: workeracoesgha
  
jobs:
  tests:

    runs-on: ubuntu-latest

    services:
      zookeeper:
        image: confluentinc/cp-zookeeper:latest
        env:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
        ports:
          - 2181:2181
      kafka:
        image: confluentinc/cp-kafka:latest
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ports:
          - 9092:9092
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: MongoDB2021!
        ports:
          - 27017:27017

    env:
      MongoDBConnection: mongodb://root:MongoDB2021!@localhost:27017
      MongoDatabase: DBAcoesTestes
      MongoCollection: HistoricoAcoesTestes
      ApacheKafka__Broker: localhost:9092
      ApacheKafka__Topic: topic-testes-acoes
      ApacheKafka__GroupId: WorkerAcoesTestes

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.202

    - name: Executar a aplicação a ser testada
      run: |
        dotnet publish ${{ env.PATH_PROJETO }} -c Release -o app
        cd ./app
        sleep 20s
        nohup dotnet WorkerAcoes.dll > ${{ env.FILE_LOG_EXECUCAO_WORKERACOES }} 2>&1 &
        sleep 10s
        ls

    - name: Execução dos testes de integração
      env:
        IntervaloProcessamento: 4000
      run: dotnet test ${{ env.PATH_PROJETO_TESTES }} --verbosity minimal --logger:"html;LogFileName=resultado-testes.html"

    - name: Upload como Artifact do Log de Execução do Worker de Ações
      uses: actions/upload-artifact@v2.2.3
      if: always()
      with:
        name: log-execucao-workeracoes
        path: ./app/${{ env.FILE_LOG_EXECUCAO_WORKERACOES }}
        retention-days: 30

    - name: Upload como Artifact do Report de Testes
      uses: actions/upload-artifact@v2.2.3
      if: always()
      env:
        CAMINHO_RELATORIO: ${{ env.PATH_PROJETO_TESTES }}/TestResults/resultado-testes.html
      with:
        name: resultado-testes
        path: ${{ env.CAMINHO_RELATORIO }}
        retention-days: 30
